// Constants is a dict of action types.
const constants = {
  // Auth
  SET_AUTH: 'SET_AUTH',
  // Privacy Policy
  FETCH_PP_BEGIN: 'FETCH_PP_BEGIN',
  FETCH_PP_SUCCESS: 'FETCH_PP_SUCCESS',
  FETCH_PP_FAILURE: 'FETCH_PP_FAILURE',
  // Terms and Conditions
  FETCH_TERMS_BEGIN: 'FETCH_TERMS_BEGIN',
  FETCH_TERMS_SUCCESS: 'FETCH_TERMS_SUCCESS',
  FETCH_TERMS_FAILURE: 'FETCH_TERMS_FAILURE',
  // User (include diets)
  FETCH_USER_BEGIN: 'FETCH_USER_BEGIN',
  FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
  FETCH_USER_FAILURE: 'FETCH_USE_FAILURE',
  // Diets
  FETCH_DIETS_BEGIN: 'FETCH_DIETS_BEGIN',
  FETCH_DIETS_SUCCESS: 'FETCH_DIETS_SUCCESS',
  FETCH_DIETS_FAILURE: 'FETCH_DIETS_FAILURE',
  // Paths (include recipes)
  FETCH_PATHS_BEGIN: 'FETCH_PATHS_BEGIN',
  FETCH_PATHS_SUCCESS: 'FETCH_PATHS_SUCCESS',
  FETCH_PATHS_FAILURE: 'FETCH_PATHS_FAILURE',
  // Nutrients
  FETCH_NUTRIENTS_BEGIN: 'FETCH_NUTRIENTS_BEGIN',
  FETCH_NUTRIENTS_SUCCESS: 'FETCH_NUTRIENTS_SUCCESS',
  FETCH_NUTRIENTS_FAILURE: 'FETCH_NUTRIENTS_FAILURE',
  // UserPath
  // UserFoods
  // UserRecipes
};

export default constants;
