// Constants is a dict of action types.
const constants = {
  // Auth
  SET_AUTH: 'SET_AUTH',
  // Privacy Policy
  FETCH_PP_BEGIN: 'FETCH_PP_BEGIN',
  FETCH_PP_SUCCESS: 'FETCH_PP_SUCCESS',
  FETCH_PP_FAILURE: 'FETCH_PP_FAILURE',
  // Terms and Conditions
  FETCH_TERMS_BEGIN: 'FETCH_TERMS_BEGIN',
  FETCH_TERMS_SUCCESS: 'FETCH_TERMS_SUCCESS',
  FETCH_TERMS_FAILURE: 'FETCH_TERMS_FAILURE',
  // User
  FETCH_USER_BEGIN: 'FETCH_USER_BEGIN',
  FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
  FETCH_USER_FAILURE: 'FETCH_USE_FAILURE',
  // Diets
  FETCH_DIETS_BEGIN: 'FETCH_DIETS_BEGIN',
  FETCH_DIETS_SUCCESS: 'FETCH_DIETS_SUCCESS',
  FETCH_DIETS_FAILURE: 'FETCH_DIETS_FAILURE',
};

export default constants;
