// Constants is a dict of action types.
const constants = {
  // Auth
  SET_AUTH: 'SET_AUTH',
  // Daily Progress
  FETCH_DAILY_PROGRESS_BEGIN: 'FETCH_DAILY_PROGRESS_BEGIN',
  FETCH_DAILY_PROGRESS_SUCCESS: 'FETCH_DAILY_PROGRESS_SUCCESS',
  FETCH_DAILY_PROGRESS_FAILURE: 'FETCH_DAILY_PROGRESS_FAILURE',
  // Diets
  FETCH_DIETS_BEGIN: 'FETCH_DIETS_BEGIN',
  FETCH_DIETS_SUCCESS: 'FETCH_DIETS_SUCCESS',
  FETCH_DIETS_FAILURE: 'FETCH_DIETS_FAILURE',
  // Nutrients
  FETCH_NUTRIENTS_BEGIN: 'FETCH_NUTRIENTS_BEGIN',
  FETCH_NUTRIENTS_SUCCESS: 'FETCH_NUTRIENTS_SUCCESS',
  FETCH_NUTRIENTS_FAILURE: 'FETCH_NUTRIENTS_FAILURE',
  // Recommended Foods
  FETCH_RECOMMENDED_FOODS_BEGIN: 'FETCH_RECOMMENDED_FOODS_BEGIN',
  FETCH_RECOMMENDED_FOODS_SUCCESS: 'FETCH_RECOMMENDED_FOODS_SUCCESS',
  FETCH_RECOMMENDED_FOODS_FAILURE: 'FETCH_RECOMMENDED_FOODS_FAILURE',
  // User
  FETCH_USER_BEGIN: 'FETCH_USER_BEGIN',
  FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
  FETCH_USER_FAILURE: 'FETCH_USE_FAILURE',
  // UserFoods
  FETCH_USERFOODS_BEGIN: 'FETCH_USERFOODS_BEGIN',
  FETCH_USERFOODS_SUCCESS: 'FETCH_USERFOODS_SUCCESS',
  FETCH_USERFOODS_FAILURE: 'FETCH_USERFOODS_FAILURE',
  // UserRecipes
};

export default constants;
