const constants = {
  CHANGE_ACTIVE_PATH: 'CHANGE_ACTIVE_PATH',
  UPDATE_CUSTOM_PATH: 'UPDATE_CUSTOM_PATH',
  ADD_USER_FOOD: 'ADD_USER_FOOD',
  DELETE_USER_FOOD: 'DELETE_USER_FOOD',
  UPDATE_USER: 'UPDATE_USER',
  ADD_USER_RECIPE: 'ADD_USER_RECIPE',
  DELETE_USER_RECIPE: 'DELETE_USER_RECIPE',
  FLAG_RECIPE: 'FLAG_RECIPE',
};

export default constants;
