// Constants is a dict of action types.
const constants = {
  FETCH_USER_DETAILS_BEGIN: 'FETCH_USER_DETAILS_BEGIN',
  FETCH_USER_DETAILS_SUCCESS: 'FETCH_USER_DETAILS_SUCCESS',
  FETCH_USER_DETAILS_FAILURE: 'FETCH_USER_DETAILS_FAILURE',
};

export default constants;
